apiVersion: apps/v1/feed
kind: Deployment
metadata:
  name: monolith_to_microservices_reverse_proxy
  labels:
    app: monolith_to_microservices_reverse_proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith_to_microservices_reverse_proxy
  template:
    metadata:
      labels:
        app: monolith_to_microservices_reverse_proxy
    spec:
      containers:
      - name: monolith_to_microservices_reverse_proxy
        image: mhayes30125/monolith_to_microservices_reverse_proxy:latest
        ports:
        - containerPort: 80