apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-to-microservices-reverse-proxy
  labels:
    app: monolith-to-microservices-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith-to-microservices-reverse-proxy
  template:
    metadata:
      labels:
        app: monolith-to-microservices-reverse-proxy
    spec:
      containers:
      - name: monolith-to-microservices-reverse-proxy
        image: mhayes30125/monolith_to_microservices_reverse_proxy:latest
        ports:
        - containerPort: 80
      restartPolicy: Always