apiVersion: v1
kind: Service
metadata:
  name: monolith_to_microservices_reverse_proxy
  labels:
    run: monolith_to_microservices_reverse_proxy
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: monolith_to_microservices_reverse_proxy