apiVersion: v1
kind: Service
metadata:
  labels:
    app: monolith-to-microservices-reverse-proxy
  name: monolith-to-microservices-reverse-proxy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: monolith-to-microservices-reverse-proxy