apiVersion: v1
kind: Service
metadata:
  name: monolith-to-microservices-reverse-proxy-svc
  labels:
    app: monolith-to-microservices-reverse-proxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: monolith-to-microservices-reverse-proxy